import type { SiteConfig } from '@/types/config'

export const siteConfig: SiteConfig = {
  categories: [
    {
      id: 'somoe-domain',
      name: 'SOMOE 域名专属项目',
      icon: 'Sparkles',
      desc: 'Somoe 域名下的专属站点项目',
      items: [
        {
          id: 'somoe-site',
          title: 'Somoe（SO萌网站）',
          description: 'somoe，个人内容聚集之地。',
          url: 'https://somoe.xyz',
          icon: 'Globe',
          tags: ['社区', '个人项目', '游戏'],
        },
        {
          id: 'somoe-vision',
          title: '视效世界',
          description: '一个视效世界',
          url: 'https://vision.somoe.xyz/',
          icon: 'Eye',
          tags: ['视效', '播放器'],
        },
        {
          id: 'ocean-book-theme',
          title: 'Ocean Book',
          description: '一个 Astro 博客主题',
          url: 'https://ocean.somoe.xyz/',
          icon: 'BookOpen',
          tags: ['astro', '主题', '博客'],
        },
        {
          id: 'viewmemo',
          title: 'ViewMemo',
          description: '一个应用原型页面设计的小工具',
          url: 'https://viewmemo.somoe.xyz/',
          icon: 'Frame',
          tags: ['设计', '应用', '编排'],
        },
        {
          id: 'ocean-blog',
          title: 'Ocean Blog',
          description: '使用 Ocean Book 主题构建的个人博客网站。',
          url: 'https://blog.somoe.xyz/',
          icon: 'BookOpen',
          tags: ['博客', '个人分享', '碎碎念'],
        },
      ],
    },
    {
      id: 'open-source',
      name: '开源项目',
      icon: 'Github',
      desc: '开源发布的工具与组件',
      items: [
        {
          id: 'mvideo-oss',
          title: 'MVideo',
          description: '一款基于 TypeScript 开发的现代化 Web 视频播放器组件，支持多种播放格式和丰富的交互功能。',
          url: 'https://mvideo.qiumonster.com/',
          icon: 'Play',
          tags: ['Video', '插件'],
        },
      ],
    },
    {
      id: 'my-projects',
      name: '我的项目',
      icon: 'Rocket',
      desc: '个人开发的项目与作品',
      items: [
        {
          id: 'mdesign',
          title: 'MDesign',
          description: '打造高性能、高颜值的现代化网页应用。极简风格，极致体验。',
          url: 'https://design.qiumonster.com/',
          icon: 'Palette',
          tags: ['设计', 'UI样式'],
        },
        {
          id: 'flow-mirror',
          title: '流镜编辑',
          description: '一个【流程脚本+可视化节点系统】的编辑器',
          url: 'https://flow-mirror.qiumonster.com',
          icon: 'GitMerge',
          tags: ['流程', '节点', '编辑'],
        },
        {
          id: 'memory',
          title: '忆文录',
          description: '讲述关于回忆的内容。',
          url: 'https://memory.qiumonster.com/',
          icon: 'FileText',
          tags: ['回忆', '文字', '记录'],
        },
        {
          id: 'mineradio',
          title: 'Mineradio',
          description: '一个沉浸式播放器项目，基于 XxHuberrr 开源的 Minradio 开发而来。',
          url: 'https://mr.qiumonster.com/',
          icon: 'Radio',
          tags: ['播放器', '视效'],
        },
        {
          id: 'vision-world',
          title: 'Vision World',
          description: '一个视效世界',
          url: 'https://vision.qiumonster.com/',
          icon: 'Eye',
          tags: ['视效', '视频'],
        },
      ],
    },
    {
      id: 'oss-repos',
      name: '我的开源仓库',
      icon: 'GitBranch',
      desc: 'Gitee 上的开源代码仓库',
      items: [
        {
          id: 'oss-ai',
          title: 'ai',
          description: '一个帮你拥有自己隐私的 AI 项目，AI 可以通过已有数据，生成新的数据内容。',
          url: 'https://gitee.com/qiustudio/ai',
          icon: 'Cpu',
          tags: ['AI', '机器学习', '隐私'],
        },
        {
          id: 'oss-mvideo',
          title: 'MVideo',
          description: '一个正在探索的视频收集整理项目',
          url: 'https://gitee.com/qiustudio/MVideo',
          icon: 'Video',
          tags: ['视频', '收集', '整理'],
        },
        {
          id: 'oss-ofd',
          title: 'ofd',
          description: '一个 Three.js 基础的 Web 程序',
          url: 'https://gitee.com/qiustudio/ofd',
          icon: 'Box',
          tags: ['Three.js', 'WebGL', '3D'],
        },
        {
          id: 'oss-qiuhexo',
          title: 'qiuhexo',
          description: '一个 Hexo 主题',
          url: 'https://gitee.com/qiustudio/qiuhexo',
          icon: 'Hexagon',
          tags: ['Hexo', '主题', '博客'],
        },
        {
          id: 'oss-astro-ocean-book',
          title: 'astro-ocean-book',
          description: 'Ocean Book，一个 Astro 博客主题',
          url: 'https://gitee.com/qiumonster/astro-ocean-book/',
          icon: 'BookOpen',
          tags: ['astro', 'blog'],
        },
      ],
    },
    {
      id: 'website-projects',
      name: '网站项目',
      icon: 'Globe',
      desc: '已上线的网站与在线服务',
      items: [
        {
          id: 'open-qiuhexo',
          title: 'OPEN-QIUHEXO',
          description: '一个开源 Hexo 主题',
          url: 'https://qiumonster.com/qiuhexo/',
          icon: 'Hexagon',
          tags: ['Hexo', '主题', '开源'],
        },
        {
          id: 'next-leave',
          title: 'NEXT LEAVE',
          description: '一个 Vite 开发的名为"未至之期"的主题，简洁，文字型，搭配。',
          url: 'https://qiumonster.com/next-leave/',
          icon: 'Leaf',
          tags: ['Vite', '主题', '博客'],
        },
        {
          id: 'qiuhexo-blog',
          title: 'QIUHEXO',
          description: '个人博客网站',
          url: 'https://blog.qiumonster.com/',
          icon: 'BookOpen',
          tags: ['博客', 'Hexo', '个人'],
        },
        {
          id: 'backrooms',
          title: '后室',
          description: '个人创建的后室社区项目',
          url: 'https://backrooms.qiumonster.com/',
          icon: 'DoorOpen',
          tags: ['游戏', '恐怖', '怪谈'],
        },
        {
          id: 'deep-ocean',
          title: '深海探索',
          description: '探索神秘的深海世界，从阳光区到深渊区，发现地球最后的未知领域',
          url: 'https://ocean.qiumonster.com/',
          icon: 'Waves',
          tags: ['科普', '海洋', '探索'],
        },
      ],
    },
  ],
}

export default siteConfig
